
#define IVI_OSC_PORT 8000
#define IVI_OSC_HOST "172.20.10.15"

#define IVI_MIDI_SHW_SPEED 1
#define IVI_MIDI_SHW_NUMDROPS 2
#define IVI_MIDI_SHW_RSHD_COPIES 3
#define IVI_MIDI_SHW_RSHD_ROTATION 4
#define IVI_MIDI_SHW_RSHD_SCALE 5

#define IVI_MIDI_RAP_NUMLINES 6
#define IVI_MIDI_RAP_DOWNRES 7
#define IVI_MIDI_RAP_DISTANCE 8
#define IVI_MIDI_RAP_BEND 9
#define IVI_MIDI_RAP_FFTAMT 10
#define IVI_MIDI_RAP_NOISEAMT 11
#define IVI_MIDI_RAP_SPEEDLINES 12
#define IVI_MIDI_RAP_JUMPBLEND 13
#define IVI_MIDI_RAP_EASEVAL 14
#define IVI_MIDI_RAP_CAMDIST 15
#define IVI_MIDI_RAP_CAMOFFSET 16
#define IVI_MIDI_RAP_CAMPITCH 17

#define IVI_MIDI_MIX_CH01 18
#define IVI_MIDI_MIX_CH02 19
#define IVI_MIDI_MIX_CH03 20
#define IVI_MIDI_MIX_CH04 21